### ISSUE TITLE
small typos that halt rmd's

### ISSUE THREAD

**Issue by yonicd** [johnros/Intro2R#1]
line 145 x seq(from=10, to=21, by=2) correct to x <- seq(from=10, to=21, by=2)
line 309 sli1ce correct to slice

**Comment by johnros** [comment]
thanks
corrected and pushed.

On Sat, Apr 25, 2015 at 8:06 PM, yonicd notifications@github.com wrote:

> line 145 x seq(from=10, to=21, by=2) correct to x <- seq(from=10, to=21,
> by=2)
> line 309 sli1ce correct to slice
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/johnros/Intro2R/issues/1.

## 

Jonathan Rosenblatt
www.john-ros.com
